# ==============================================================
# = Pincio Web Service
# ==============================================================
spring:
  profiles:
    active: "heroku"

     
---
spring:
  profiles: local
logging:
  level:
    ROOT: ERROR
    org:
      apache:
        tomcat: DEBUG
        catalina: DEBUG
server:
  tomcat:
    accesslog:
      enabled: true
---
spring:
  profiles: heroku
  datasource:
    #initialization-mode: always
    password: ${DB_PW}
    platform: mysql
    url: ${DB_URL}
    username: ${DB_USER}
    driverClassName: com.mysql.cj.jdbc.Driver
    #tomcat:
      #max-wait: 20000
      #max-active: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  
  