# ==============================================================
# = Pincio Web Service
# ==============================================================
spring:
  profiles:
    active: "heroku"

---

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka
spring:
  application:
    name: telegrambot
  security:
    user:
      password: ${PINCIO_PASSWORD:password}
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: 80
  password: ${EUREKA_USER_PASSWORD:password}
  